# Question:01

In [ ]:
import numpy as np
A = np.arange(2,50,3)
print(A)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question:02

In [ ]:
import numpy as np
A = []
B = []
for i in range(5):
    x = int(input())
    A.append(x)
for q in range(5):
    y = int(input())
    B.append(y)
a = np.array(A)
b = np.array(B)
c = np.concatenate((a,b))
print('List1:',a)
print('List2:',b)
print('concatenated:',c)
print('sorted:',np.sort(c))

1
2
6
8
5
7
12
11
10
9
List1: [1 2 6 8 5]
List2: [ 7 12 11 10  9]
concatenated: [ 1  2  6  8  5  7 12 11 10  9]
sorted: [ 1  2  5  6  7  8  9 10 11 12]


# Question:03

In [ ]:
import numpy as np
arr = np.array([ [1,2,3], [4,5,6], [7,8,9] ]) 
dimension = arr.ndim
size = arr.size
print(arr)
print('Dimension:',dimension)
print('Size:',size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2
Size: 9


# Question:04

In [ ]:
import numpy as np
A = np.array([1,2,3,4,5,6,7,8])
print(A)
print('Dimension:', A.ndim)
B = A[: , np.newaxis]
print(B)
print('Dimension:', B.ndim)

[1 2 3 4 5 6 7 8]
Dimension 1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Dimension 2


OR we can use 'np.expand_dims'

In [ ]:
import numpy as np
A = np.array([1,2,3,4,5,6,7,8])
print(A)
print('Dimension:', A.ndim)
B = np.expand_dims(A, axis=1)
print(B)
print('Dimension:', B.ndim)

[1 2 3 4 5 6 7 8]
Dimension: 1
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
Dimension: 2


# Question:05

In [ ]:
import numpy as np
arr1 = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
arr2 = np.array([ [10,11,12], [13,14,15], [16,17,18,] ])
#vertically stacking the two square numpy arrays
Vstack = np.vstack([arr1, arr2])
#horizonatally stacking the two square numpy arrays
Hstack = np.hstack([arr1, arr2])
print('Vertical Stacking:\n',Vstack)
print('Horizontal Stacking:\n',Hstack)

Vertical Stacking:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Horizontal Stacking:
 [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# Question:06

We can get the unique items and count of the unique items using a numpy attribute which is numpy.unique() and print the unique items and count of the unique items in the formm of array using an attribute numpy.asarray()

In [ ]:
import numpy as np
arr = np.array([1,1,1,2,3,4,4,3,2,2,5,7,7,7,7,8])
x, y= np.unique(arr, return_counts=True)
# x = Unique value and y = count of unique value(frequency)
z = np.asarray((x,y)).T
print(z)

[[1 3]
 [2 3]
 [3 2]
 [4 2]
 [5 1]
 [7 4]
 [8 1]]
